# Generated by Django 3.2.6 on 2023-01-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.IntegerField(default=2, verbose_name='User id'),
        ),
    ]
