# Generated by Django 3.2.6 on 2023-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230104_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('p', 'Photo'), ('f', 'Document'), ('l', 'Link')], default='Link', max_length=6),
        ),
    ]
