# Generated by Django 3.2.6 on 2023-01-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230127_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='file_type',
            new_name='file_type1',
        ),
    ]
