# Generated by Django 3.2.6 on 2023-01-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_file_type_note_file_type1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='file_type1',
            new_name='file_type',
        ),
    ]
