# Generated by Django 3.2.6 on 2023-01-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_file_type1_note_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='note_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.note'),
        ),
    ]
