# Generated by Django 3.2.6 on 2023-01-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_document_note_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='note_file',
        ),
        migrations.AddField(
            model_name='document',
            name='note_file',
            field=models.ManyToManyField(null=True, to='main.Note'),
        ),
    ]
