# Generated by Django 3.2.6 on 2023-01-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230127_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
