# Generated by Django 3.2.6 on 2023-01-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230128_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='note_file',
        ),
        migrations.AlterField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
