# Generated by Django 3.2.6 on 2023-01-28 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_note_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='x',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
