# Generated by Django 3.2.6 on 2023-02-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_note_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='x',
        ),
    ]
